version: 2.1.1-beta{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: sbStw71imn5c9ATjfPvDotgSyReJHM+il7wz8/083Xy3BONRyRxIg0cOjGAr8evI
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd src

    dotnet restore

    nuget restore

    #dotnet build Tests.net45\Tests.net45.csproj -c Release 

    dotnet build -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE"

    #dotnet pack geschikt\geschikt.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE" --include-symbols

    #dotnet pack -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE" --include-symbols --no-build

    #dotnet build geschikt.Standard\geschikt.Standard.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE"

    dotnet pack geschikt.Standard\geschikt.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE" --include-symbols
    dotnet pack geschikt.Standard\geschikt.Standard.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_PULL_REQUEST_TITLE" --include-symbols

    if(Test-Path .\Tools) {

    	Remove-Item -Recurse -Force .\Tools

    }

    nuget install coveralls.net -Version 0.7.0 -OutputDirectory Tools

    nuget install OpenCover -Version 4.6.519 -OutputDirectory Tools

    Tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -oldStyle -target:"nunit3-console.exe" -targetargs:"Tests.net45.dll" -targetdir:Tests.net45\bin\Release\ -output:coverage.xml -filter:"+[*Tests*]*" -searchdirs:Tests.net45\bin\Release\

    tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml
test: off
artifacts:
- path: src\geschikt.Standard\bin\Release\netstandard1.0\geschikt.Standard.???
  name: netstandard1.0
- path: src\geschikt.Standard\bin\Release\netstandard1.4\geschikt.Standard.???
  name: netstandard1.4
- path: src\geschikt\bin\Release\netcoreapp1.1\geschikt.???
  name: net40
- path: src\geschikt\bin\Release\net45\geschikt.???
  name: net45
- path: '**\bin\release\*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
  on:
    branch: master