version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: src\geschikt\bin\Release\geschikt.dll
  name: net40-client
- path: src\geschikt.net45\bin\Release\geschikt.dll
  name: net45
- path: '**\*.nupkg'
  name: nuget